AWSTemplateFormatVersion: "2010-09-09"
Description: Application level DNS resources

Parameters:
  ApplicationName:
    Type: String
    Description: The name of the application 

Resources:
  DNS: 
    Type: "AWS::Route53::HostedZone"
    Properties: 
      HostedZoneConfig: 
        Comment: "Hosted zone for use-mission-control.com"
      Name: "use-mission-control.com"

Outputs:
  ApplicationHostedZone:
    Description: The the root hosted zone for the application
    Value: !Ref DNS
    Export:
      Name: !Sub ${ApplicationName}-HostedZone
  